name = "labex-cheatsheets"
compatibility_date = "2025-01-21"
main = "worker.ts"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[[kv_namespaces]]
binding = "PYTHONCHEATSHEET_QUIZ_KV"
id = "660dcb67f4fa4ddf8704a733c239b374"

[[routes]]
pattern = "labex.io/cheatsheets/*"
zone_name = "labex.io"

[[routes]]
pattern = "labex.io/cheatsheets"
zone_name = "labex.io"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
